// <auto-generated />
using System;
using Commissions.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commissions.Infrastructure.Migrations
{
    [DbContext(typeof(CommissionsDBContext))]
    [Migration("20260916095740_AddBrokerTiers")]
    partial class AddBrokerTiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commissions.Core.Batch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ExpectedRowCount")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RejectedRowCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BatchId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Commissions.Core.BrokerTier", b =>
                {
                    b.Property<string>("BrokerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrokerId");

                    b.ToTable("BrokerTiers");

                    b.HasData(
                        new
                        {
                            BrokerId = "B100",
                            Multiplier = 1.20m,
                            Tier = "Gold"
                        },
                        new
                        {
                            BrokerId = "B200",
                            Multiplier = 1.10m,
                            Tier = "Silver"
                        },
                        new
                        {
                            BrokerId = "B300",
                            Multiplier = 1.00m,
                            Tier = "Bronze"
                        },
                        new
                        {
                            BrokerId = "B400",
                            Multiplier = 0.95m,
                            Tier = "Standard"
                        });
                });

            modelBuilder.Entity("Commissions.Core.ProcessedRow", b =>
                {
                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrokerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RowId", "BatchId");

                    b.HasIndex("BatchId");

                    b.ToTable("ProcessedRows");
                });

            modelBuilder.Entity("Commissions.Core.RawRow", b =>
                {
                    b.Property<string>("RowId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrokerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CommissionRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsParseable")
                        .HasColumnType("bit");

                    b.Property<long>("LineNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("ParseError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PremiumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId", "BatchId");

                    b.HasIndex("BatchId");

                    b.ToTable("RawRows");
                });

            modelBuilder.Entity("Commissions.Core.RawRow", b =>
                {
                    b.HasOne("Commissions.Core.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
